modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/3ColumnsC/NoMobsThankYou/issues"

[[mods]]
modId = "nomobsthankyou"
version = "${file.jarVersion}"
displayName = "NoMobsThankYou"
authors = "3C Team"
description = "Prevents unwanted mobs from spawning via JSON presets and override lists."
iconFile = "assets/nomobsthankyou/icon.png"
bannerFile = "assets/nomobsthankyou/icon.png"
displayURL = "https://modrinth.com/mod/nomobsthankyou"

[[mixins]]
config = "nomobsthankyou.mixins.json"

[[dependencies.nomobsthankyou]]
modId = "neoforge"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nomobsthankyou]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"
